//
//  AIKitExamplesView.swift
//  AIKit (Generated by SwiftyLaunch 1.5.0)
//  https://docs.swiftylaun.ch/module/aikit
//

import AnalyticsKit
import SharedKit
import SwiftUI

enum AIKitExamplePath: Hashable, Equatable {
	case chat  // AIChatExampleView
}

// Dashboard of all AIKit Example Views
public struct AIKitExamplesView: View {

	@State private var path = NavigationPath()

	public init() {}

	/// Reset path (go back to root)
	func popToRoot() {
		path = NavigationPath()
	}

	public var body: some View {
		NavigationStack {
			ScrollView {
				VStack(spacing: 10) {

					AIExampleCard(
						icons: ["bubble.left.and.bubble.right", "brain"],
						title: "Chatty",
						description: "Chat with AI",
						path: .chat
					)

				}
				.padding(.horizontal)
			}

			.navigationTitle("AIKit Examples")
			.navigationDestination(for: AIKitExamplePath.self) { path in
				switch path {
					case .chat:
						AIChatExampleView(popToRoot: popToRoot)
				}
			}
			.captureViewActivity(as: "AIKitExamplesView")
		}
	}
}

struct AIExampleCard: View {
	let icons: [String]
	let title: LocalizedStringKey
	let description: LocalizedStringKey
	let path: AIKitExamplePath

	var body: some View {
		NavigationLink(value: path) {
			VStack {
				HStack(spacing: 10) {
					ForEach(icons, id: \.self) { icon in
						Image(systemName: icon)
							.font(.system(size: 60, weight: .semibold))
							.foregroundStyle(Color.accentColor.gradient)
					}
				}

				Text(title)
					.font(.system(size: 40, weight: .bold))
					.fontWeight(.semibold)
					.foregroundStyle(Color.accentColor.gradient)

				Text(description)
					.foregroundStyle(.secondary)
					.font(.caption)
			}
			.padding()
			.frame(maxWidth: .infinity)
			.accentBackground()
			.clipShape(RoundedRectangle(cornerRadius: 25, style: .continuous))
			.overlay {
				RoundedRectangle(cornerRadius: 25, style: .continuous)
					.stroke(.tertiary, lineWidth: 1)
			}
			.overlay {
				HStack {
					Spacer()
					Image(systemName: "chevron.right")
						.font(.system(size: 20, weight: .semibold))
						.foregroundStyle(.tertiary)
						.padding(.trailing)
				}
				.frame(maxWidth: .infinity)
			}
		}
		.buttonStyle(.plain)
	}
}

#Preview {
	AIKitExamplesView()
}
