//
//  UIImage+Extensions.swift
//  AIKit (Generated by SwiftyLaunch 1.5.0)
//

import UIKit

extension UIImage {
	/// Convert a UIImage to base64 string in order to be able to send it to a server.
	var base64: String? {
		self.jpegData(compressionQuality: 1)?.base64EncodedString()
	}
}
